apiVersion: apps/v1
kind: Deployment
metadata:
  name: clearml-agent-k8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clearml-app
  template:
    metadata:
      labels:
        app: clearml-app
    spec:
      containers:
      - name: clearml-container
        image: docker.io/scheckley/clearml-agent
        resources:
          limits:
            cpu: '8'
            memory: '64Gi'
            nvidia.com/gpu: '1'
          requests:
            cpu: '8'
            memory: '64Gi'
            nvidia.com/gpu: '1'
