apiVersion: v1
kind: Service
metadata:
  name: clearml-agent-service
  labels:
    app: clearml-agent
spec:
  selector:
    app: clearml-agent
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
  type: ClusterIP

