apiVersion: apps/v1
kind: Deployment
metadata:
  name: clearml-agent-k8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clearml-app
  template:
    metadata:
      labels:
        app: clearml-app
    spec:
      containers:
        - name: clearml-agent
          image: dockerhub.io/scheckley/clearml-agent
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 443
              protocol: TCP
          envFrom:
            - secretRef:
                name: clearml-api-host
          resources:
            limits:
              cpu: '8'
              memory: '64Gi'
              nvidia.com/gpu: '1'
            requests:
              cpu: '4'
              memory: '32Gi'
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      nodeSelector:
        kubernetes.io/hostname: 'ocp-8q24t-worker-gpu-a100x4-2slpc'

